[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  included_files = ["emailpass.txt"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/admin/login"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/admin/logout"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/admin/api/*"
  to = "/.netlify/functions/api"
  status = 200
